dist: trusty
sudo: false
language: cpp
compiler: gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libc++-dev
      - libc++-helpers
      - libc++1
      - cmake
      - libboost1.55-dev
      - libboost1.55-tools-dev
      - libboost1.55-all-dev
      - gcc-5
      - g++-5

script:
  - export CXX=g++-5
  - export CC=gcc-5
  - mkdir build
  - cd build
  - cmake .. -DBUILD_SSL=YES -DCMAKE_BUILD_TYPE=Debug
  - make -j4
